### PR TITLE
Include support info for Serif CJK

### PR DESCRIPTION
**Pull request by mi2ebi**

### CODE REVIEW

**Comment by berrymot** [comment]
about the CLA- I'm trans, does it want my legal name or preferred one

**Comment by mi2ebi** [comment]
signed :3

**Comment by mi2ebi** [comment]
realized this got rid of the emoji data oops

**Comment by mi2ebi** [comment]
fixed i hope!

**Comment by mi2ebi** [comment]
gonna close this & open kne that doesn't cause merge conflicts later

**Pull request closed without merging**
